### ISSUE TITLE
Error when running npm run dev

### ISSUE THREAD

**Issue by sovereignhodler** [royalfig/ghost-theme-starter#1]
I get the following output (running a local install of ghost on Pop OS)

`rollup v2.62.0
bundles src/js/app/index.js → assets/built/app.js...
[!] (plugin postcss) Error: Failed to find './layout/footer.css'
  in [
    /home/thibaut/ghost/themes/ghost-theme-starter/src/css
  ]
src/css/app.css
Error: Failed to find './layout/footer.css'
  in [
    /home/thibaut/ghost/themes/ghost-theme-starter/src/css
  ]
    at /home/thibaut/ghost/themes/ghost-theme-starter/node_modules/postcss-import/lib/resolve-id.js:35:13
    at LazyResult.runAsync (/home/thibaut/ghost/themes/ghost-theme-starter/node_modules/postcss/lib/lazy-result.js:396:11)

bundles src/js/post/index.js → assets/built/post.js...
(!) Generated an empty chunk
index
created assets/built/post.js in 35ms`

**Comment by royalfig** [comment]
Added the missing footer style with latest commit. Update and you should be good to go. Thanks!
